name: university_system_front
description: "Flutter Frontend for UniversitySystem"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  firebase_core: ^3.1.1
  go_router: ^14.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  simple_animations: ^5.0.2
  get_it: ^7.7.0
  window_manager: ^0.3.9
  bitsdojo_window: ^0.1.6
  flutter_adaptive_scaffold: ^0.1.11+1
  dart_mappable: ^4.2.2
  mutex: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.25.2
  flutter_native_splash: ^2.4.0
  dart_jsonwebtoken: ^2.14.0
  mockito: ^5.4.4
  # Linters
  flutter_lints: ^4.0.0
  custom_lint:
  riverpod_lint: ^2.3.10
  # build_runner dependencies
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  dart_mappable_builder: ^4.2.3

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Blazma
      fonts:
        - asset: fonts/blazma/Blazma-Regular.ttf
        - asset: fonts/blazma/Blazma-Italic.ttf
          style: italic

  assets:
    - assets/splash_logo.png #Splash image A
    - assets/logo.png #Splash image B
    - assets/logo_full_nobg_v1.png #Splash image C
    - assets/logo_no_shadow_rotated.png

# To regenerate the splashScreen the following is needed:
# -> Image A, splashScreen that follows the Android 12 requirements for app icon without an icon background
#    see https://developer.android.com/develop/ui/views/launch/splash-screen
# -> Image B, centered logo of "A" image in every pixel density following the exact size as the logo occupies in the "A" image
# -> Image C, the logo in the final size
flutter_native_splash:
  color: "#404942"
  image: assets/splash_logo.png #This is image A
  android_12:
   image: assets/splash_logo.png
   color: "#404942"
  ios: false
  web: false
  android_screen_orientation: portrait
